# coding: utf-8

"""
    news-sender

    Сервис для отправки новостей пользователям

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from endpoints.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="news-sender",
    description="Сервис для отправки новостей пользователям",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
