version: '3.6'
services:
  service:
    build:
      context: .
      target: service
    environment:
       - MONGO_PASSWORD
       - MONGO_HOST
       - TG_TOKEN
    ports:
      - "8080:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
