# coding: utf-8

# flake8: noqa

"""
    ml-processor

    Сервис для взаимодействия со всеми ML моделями

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from ml_processor_client.api.default_api import DefaultApi

# import ApiClient
from ml_processor_client.api_response import ApiResponse
from ml_processor_client.api_client import ApiClient
from ml_processor_client.configuration import Configuration
from ml_processor_client.exceptions import OpenApiException
from ml_processor_client.exceptions import ApiTypeError
from ml_processor_client.exceptions import ApiValueError
from ml_processor_client.exceptions import ApiKeyError
from ml_processor_client.exceptions import ApiAttributeError
from ml_processor_client.exceptions import ApiException

# import models into sdk package
from ml_processor_client.models.get_greeting200_response import GetGreeting200Response
