# coding: utf-8

# flake8: noqa
"""
    ml-processor

    Сервис для взаимодействия со всеми ML моделями

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ml_processor_client.models.get_greeting200_response import GetGreeting200Response
