# coding: utf-8

# flake8: noqa
"""
    news-parser

    Парсер новостей из тг каналов

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from news_parser_client.models.get_greeting200_response import GetGreeting200Response
