# coding: utf-8

# flake8: noqa
"""
    telegram-bot

    Сервис для взаимодействия с телеграммом

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from telegram_bot_client.models.get_greeting200_response import GetGreeting200Response
from telegram_bot_client.models.get_greeting200_response_tg_bot_thing import GetGreeting200ResponseTgBotThing
