# coding: utf-8

# flake8: noqa

"""
    example-service-skeleton

    A simple service that returns a greeting and current time.

    The version of the OpenAPI document: 1.0.0
    Contact: we_dont_care@kys.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from example_service_skeleton_client.api.greeting_api import GreetingApi

# import ApiClient
from example_service_skeleton_client.api_response import ApiResponse
from example_service_skeleton_client.api_client import ApiClient
from example_service_skeleton_client.configuration import Configuration
from example_service_skeleton_client.exceptions import OpenApiException
from example_service_skeleton_client.exceptions import ApiTypeError
from example_service_skeleton_client.exceptions import ApiValueError
from example_service_skeleton_client.exceptions import ApiKeyError
from example_service_skeleton_client.exceptions import ApiAttributeError
from example_service_skeleton_client.exceptions import ApiException

# import models into sdk package
from example_service_skeleton_client.models.get_greeting200_response import GetGreeting200Response
