# coding: utf-8

# flake8: noqa
"""
    example-service-skeleton

    A simple service that returns a greeting and current time.

    The version of the OpenAPI document: 1.0.0
    Contact: we_dont_care@kys.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from example_service_skeleton_client.models.get_greeting200_response import GetGreeting200Response
