# coding: utf-8

"""
    example-service-skeleton

    A simple service that returns a greeting and current time.

    The version of the OpenAPI document: 1.0.0
    Contact: we_dont_care@kys.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from endpoints.apis.greeting_api import router as GreetingApiRouter

app = FastAPI(
    title="example-service-skeleton",
    description="A simple service that returns a greeting and current time.",
    version="1.0.0",
)

app.include_router(GreetingApiRouter)
