# coding: utf-8

# flake8: noqa

"""
    telegram-bot

    Сервис для взаимодействия с телеграммом

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from telegram_bot_client.api.default_api import DefaultApi

# import ApiClient
from telegram_bot_client.api_response import ApiResponse
from telegram_bot_client.api_client import ApiClient
from telegram_bot_client.configuration import Configuration
from telegram_bot_client.exceptions import OpenApiException
from telegram_bot_client.exceptions import ApiTypeError
from telegram_bot_client.exceptions import ApiValueError
from telegram_bot_client.exceptions import ApiKeyError
from telegram_bot_client.exceptions import ApiAttributeError
from telegram_bot_client.exceptions import ApiException

# import models into sdk package
from telegram_bot_client.models.get_greeting200_response import GetGreeting200Response
from telegram_bot_client.models.get_greeting200_response_tg_bot_thing import GetGreeting200ResponseTgBotThing
