apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-processor
  template:
    metadata:
      labels:
        app: ml-processor
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: ml-processor
        image: {{ .Values.werf.image.ml_processor }}
        command: ["uvicorn"]
        args: ["endpoints.main:app", "--host", "0.0.0.0", "--port", "8080"]
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_HOST
            value: {{ .Values.mongoHost | quote }}
          - name: MONGO_PASSWORD
            value: {{ .Values.mongoPassword | quote }}
          - name: TG_TOKEN
            value: {{ .Values.tgToken | quote }}
          - name: TG_API_ID
            value: {{ .Values.tgApiId | quote }}
          - name: TG_API_HASH
            value: {{ .Values.tgApiHash | quote }}